import { Component } from '@angular/core';

@Component({
  selector: 'app-random',
  template: `
    <p>
      random works!
    </p>
  `,
  styles: [
    `
      :host {
        display: block;
      }
    `
  ]
})
export class RandomComponent {

}


/**
 *
 *  home -> welcome.component.ts
 *  ** -> not-found.component.ts
 *
 *
 * We want a menu with a blue border and a light blue background
 * Display block, no test, all of this, generated by the CLI command.
 */
